# Generated by Django 4.2.3 on 2023-08-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=59)),
                ('last_name', models.CharField(max_length=34)),
                ('phone_number', models.CharField(max_length=34)),
                ('emil', models.EmailField(max_length=56)),
                ('content', models.CharField(max_length=34)),
            ],
        ),
    ]
