# Generated by Django 4.2.3 on 2023-09-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_contec_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300, unique=True)),
                ('last_name', models.CharField(max_length=300, unique=True)),
                ('phone_number', models.CharField(max_length=300, unique=True)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Contec',
        ),
    ]
